### ISSUE TITLE
Opening Orion on Lord - List

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#116]
Hi Galen 

Please see attached

Ethan opens o.k
Orion hangs

Thank you
AA

![feedback](https://cloud.githubusercontent.com/assets/7224727/15227633/7ba0522a-18cb-11e6-86b4-5d016c0873a7.png)

**Comment by galenp** [comment]
So there was a script error occurring on the Lord properties. 
That's been fixed and pushed to the live site.

Certainly wasn't an issue or slowness LOADING the properties from the server... but instead the issue was formatting the links. This caused an error that was visible in the debugger console (F12).
