### ISSUE TITLE
Print report

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#118]
Hello Galen

please see attached, can not print/ view report/ price list

AA

![feeback26th](https://cloud.githubusercontent.com/assets/7224727/15556716/b7ef81aa-2312-11e6-8664-0d46fd8a98ce.png)

**Comment by galenp** [comment]
Ok it's not a serious issue but something to do with the download link not correctly generating the right address.

The report server has correctly placed the following report:
https://s3-ap-southeast-2.amazonaws.com/collect.propertycompass.com.au/property-lists/f93ff345-32ff-4a31-8b9e-a02b1ed6408e/Mason-SQ-Hall-St-Moonee-Ponds.pdf

Notice the link from your screen shot has a double hyphen. This is probably due to a hyphen being in the name of the Property List or something else.

I'll have it fixed in the next upload of PC2 from end.

**Comment by galenp** [comment]
Should be fixed now.

https://bitbucket.org/propertycompass/pc.client.web/commits/67a4a74ad24d3a630c2e7488aaadf75f6398dfe7
