### ISSUE TITLE
Property details - collect data screen - Part 4

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#15]
See attached

Thank you
AA
![propertydetails-collect-part-4](https://cloud.githubusercontent.com/assets/7224727/7388356/c56ca8ee-eea7-11e4-9560-4b73f53b84f3.png)

**Comment by anthonyaoun** [comment]
actually internal and external both need changing; no need for the arrows

**Comment by galenp** [comment]
The arrows are because the INPUT for this field is type Number
Some browsers automatically put those arrows in there (not all browsers do it tho).. It's not a programmatic thing done by me.

I can change the INPUT to be type TEXT (this removes the arrows that appear on some browsers) but then I will need to add validation to ensure that only a number is entered in this field.
