### ISSUE TITLE
ipr - VillaWorld - Launch

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#28]
Galen

Please see attached Upload the PDF copy here.

Please resolve this display issue; we can not rely 100% on Google to find an ADDRESS hence we need a parallel solution. 

Hopefully this is the first of many advertisements. 

Thank you
AA

![ipr-feedback-villaworld](https://cloud.githubusercontent.com/assets/7224727/7426927/056d54da-f014-11e4-9341-89b02897f989.png)

**Comment by galenp** [comment]
please dont log PC1 issues in here. Use Trac for that.

**Comment by galenp** [comment]
Hi Mate

Please refere to the very length e-mail I wrote describing the involved steps for correctly setting a property address for proper formatting in PropData and IPR.

There is NO google matching in PC1 so that has nothing to do with this issue. And nothing to do with PC2.

There is no Estate.Street set properly set... as in there is an Estate.Street... it's a single space. So its not EMPTY its using that SPACE as the value for the street.
