### ISSUE TITLE
PC 1 - Business admin

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#32]
Please see attached

AA

![2 0iprlaunch-pc1-admin-menu-other](https://cloud.githubusercontent.com/assets/7224727/7451596/cf7f522c-f295-11e4-856e-157ae0f8733a.png)

**Comment by galenp** [comment]
Hi Mate

I spent several hours on this flow tonight.. without even this image. As I mentioned on the phone I don't think the existing PC1 flow for getting a user to an IPR button is adequate. So I've extended the bridging application to have an interface for selecting the property to Order an IPR.

Some screen grabs:
![image](https://cloud.githubusercontent.com/assets/1113659/7457771/b57c4930-f2c1-11e4-9abd-248ade4b5b7b.png)

![image](https://cloud.githubusercontent.com/assets/1113659/7457777/bf8314ea-f2c1-11e4-8e3a-95ab748ccbad.png)

![image](https://cloud.githubusercontent.com/assets/1113659/7457789/cae7fdc8-f2c1-11e4-9cba-a88b74aee07d.png)

**Comment by galenp** [comment]
Flows that need review:

1) First time a user clicks into the Bridging application we have a profile migration process... essentially this imports the Business Admin user from PC1 and prompts the user to confirm details by storing the details as a PC2 user. Note the e-mail is LOCKED to the @cpx.net.au address of the Business Admin user.

2) At the completion of this 'migration' process the user should freely be able to access the bridging application from the PC1 menus. Additionall the user will be able to log into PC2 with the credentials they provided.

3) The Order IPR (or Buy IPR) still needs to present 2 choices to the user... 1. from existing stock, or 2. click to access PC to order for a property that is not listed.

4) When you order from an existing property you are first presented with an import interface that sucks the details from PC1 allowing the user to **confirm** them. Note tho... this import process purely just populates the Buy Review screen... so the user can completely alter the details again within PC2. I want this to be clear ... we don't have to invest unreasonable time having the IMPORT interface 100% because there is still the standard EDIT/SUBMIT interface that is used in this flow. That being said.. if the fields are correctly set in PC1 then we should import them all correctly.

ps:  I'm still working on the coverage for all these fields... but you can see from the updated interface the direction it's going.

**Comment by galenp** [comment]
The Business Admin links are available in production but only for the CPX BPLS at the moment.

Tomorrow (when we are both online) I want to delete the centralpropertyexchange@cpx.net.au user from PC2 so you can test the migration process.
