### ISSUE TITLE
Country selector

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#76]
![pc-07](https://cloud.githubusercontent.com/assets/7224727/11450661/58b190b4-95fc-11e5-8da9-6267992128ff.png)

**Comment by galenp** [comment]
Ok so REA which is what we are building towards supports:

Australia
and Some New Zealand support only

All of their UI leaves country OFF the listing display as it's assumed.

Perhaps this is changed if the country is not Australia (which would make sense) but I've yet to see a non AU listing to compare against.

I've tried to mirror REA without imposing limitations. 

I think listing of non AU stock should work out of Property Compass from day 1. However problems will occur if that stock is attempted to be sent to REA.

I don't want to impose REA validation in the front end... I don't want to say... "hey you have a foreign listing this cant be published to REA" as that becomes unmanagement. Instead the REA publish option would remain but their validation errors would trigger a failure that we could show.

So that's kind of where we are at.... PC should support foreign listings but in terms of the Display and publishing its limited to AU.

**Comment by galenp** [comment]
For now I think we accept an Australian Listing limitation on Property Compass until there is a business case to expand to overseas listings.

While I would avoid design decisions that region lock us to Australia... I don't want to constantly think about localization challenges during this stage of our development because it will slow everything down.
