### ISSUE TITLE
Missing List Name in feeds

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#90]
please see attached

![listname](https://cloud.githubusercontent.com/assets/7224727/14412688/7fb3b3d6-ffab-11e5-9d30-afcb7a2545ef.png)

**Comment by galenp** [comment]
So the idea is on the Personal Feed we need to show the Property List name to give context for each notification.

Within the Property List details feed the context is a given since you are viewing the notifications inside the details of a Property List.

Now whether this presents a usability challenge or not I'm still open to discuss.

**Comment by anthonyaoun** [comment]
I retested and it is a non issue
